# netlify.toml - placed in your project root
[build]
  publish = "docs/.vuepress/dist"
  command = "npm run docs:build"

# Redirect/Rewrite Rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true # Added 'force' to ensure it takes precedence