backend:
  name: git-gateway
  branch: main # Or 'main' if that's your default branch

publish_mode: editorial_workflow # Recommended for review process

media_folder: "docs/.vuepress/public/uploads" # Path to media files, relative to the project root
public_folder: "/uploads" # Path to media files, relative to the site root

collections:
  - name: "voorschrijven" # A name for your collection
    label: "Voorschrijven" # Label in the CMS UI
    folder: "docs/voorschrijven" # The folder where your articles live (e.g., your VuePress docs folder)
    create: true # Allow users to create new articles
    slug: "{{slug}}" # How filenames are generated
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "toedienregistratie" # A name for your collection
    label: "Toedienregistratie" # Label in the CMS UI
    folder: "docs/toedienregistratie" # The folder where your articles live (e.g., your VuePress docs folder)
    create: true # Allow users to create new articles
    slug: "{{slug}}" # How filenames are generated
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "koppeling-ysis" # A name for your collection
    label: "Koppeling Ysis" # Label in the CMS UI
    folder: "docs/beheer/koppelingen/ysis" # The folder where your articles live (e.g., your VuePress docs folder)
    create: true # Allow users to create new articles
    slug: "{{slug}}" # How filenames are generated
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "koppeling-algemeen" # A name for your collection
    label: "Koppeling Algemeen" # Label in the CMS UI
    folder: "docs/beheer/koppelingen/algemeen" # The folder where your articles live (e.g., your VuePress docs folder)
    create: true # Allow users to create new articles
    slug: "{{slug}}" # How filenames are generated
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
